AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::Synthetics::Group resource type

Globals:
  Function:
    Timeout: 240  # docker start-up times can be long for SAM CLI
    MemorySize: 512

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazon.synthetics.group.HandlerWrapper::handleRequest
      Runtime: java17
      CodeUri: ./target/aws-synthetics-group-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazon.synthetics.group.HandlerWrapper::testEntrypoint
      Runtime: java17
      CodeUri: ./target/aws-synthetics-group-handler-1.0-SNAPSHOT.jar

